version: '3.8'

services:
  mongo:
    image: mongo:5.0
    restart: always
    container_name: shoe-store-mongo
    hostname: host-mongo
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: shoe-store
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

